name: Build Tokenizers Wheel

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write  # ✅ REPLACE 'workflows' with 'actions'

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
      - name: Create wheels directory
        run: mkdir -p wheels

      - name: Build tokenizers wheel
        run: pip wheel tokenizers==0.13.3 -w wheels

      - name: Verify wheel creation
        run: ls -l wheels

      - name: Commit and push wheel
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add wheels
          git commit -m "Build: Update tokenizers wheel"
          git push
